name: WindowsBuild

on: [push]

jobs:
  build_windows:
    runs-on: windows-2019
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: build project
      run: ./ci/build_release_windows.bat
    - uses: actions/upload-artifact@v3
      with:
        name: 4k_executables_windows
        path: build_dir/*.exe